### ISSUE TITLE
/vagrant/installation.sh seems to be missing for stable?

### ISSUE THREAD

**Issue by beddari** [owncloud-archive/acceptance-testing#11]
Was interested in how installation was automated but this file seems to be missing? I get

<pre>err: /Stage[main]/Sources::Stable4/Exec[installation]/returns: change from notrun to 0 failed: /bin/sh: 0: Can't open /vagrant/installation.sh<pre>

**Comment by DeepDiver1975** [comment]
Have a look at https://github.com/owncloud/acceptance-testing

**Comment by diederikdehaas** [comment]
@DeepDiver1975 Care to clarify your comment? 
Since beddari reported the issue in that/this very repository, my guess is, he already found it ;-)

**Comment by DeepDiver1975** [comment]
hehe - sorry the link is wrong - my fault. Sorry for that!
Currently only testing git master works - I should remove the stable4 configs.

In order to get acceptance testing for master up and running - please have a look at :
https://github.com/owncloud/acceptance-testing/blob/master/test-master.sh
