### ISSUE TITLE
Too many configurations, tests and the setup in Jenkins is not working

### ISSUE THREAD

**Issue by Gomez** [owncloud-archive/acceptance-testing#19]
Today i worked with @DeepDiver1975 on getting the tests pass and make a working Jenkins config.

We came to the conclusion there are to many vagrant configurations (apache,nginx,mysql....). We should concentrate on one config (apache, sqlite) and get this fully working in jenkins, with all tests pass. This setup should be the "master" and we should iterate from there.

Does this sound like a plan? Any comments?

**Comment by jakobsack** [comment]
Hi, could you please point me to the things that do not work? I know that the nginx environment does not work but the rest is ok AFAIK.

**Comment by Gomez** [comment]
I haven't tested all environments. I was just beaten by that many setups/environment and configurations. First thing was to find a way to run only one test on one configuration. 
Than i noticed some tests fail and many tests aren't implemented. So i think we should go for a "master" config, make all tests work (with jenkins), and than add more environments.

PS: You have done great work! I think we should first concentrate on one environment.

**Comment by jakobsack** [comment]
Ok. I totally aggree with you that we should concentrate on one platform first.

In theory the tests should pass in the other environments anyway.

**Comment by Gomez** [comment]
New master has only one config, we will add more as soon as the workflow with jenkins etc. works
