### ISSUE TITLE
print sha of last commit after installing from github

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud-archive/acceptance-testing#20]
`git rev-parse HEAD`

this is what we need to print out somewhere.

@jakobsack can you please give be a quick hint where? THX

**Comment by jakobsack** [comment]
Add a script with the following content:

``` bash
echo -n "core " >> /var/www/versions.txt
cd /usr/local/src/owncloud-core; git log -1 --format="%H" >> /var/www/versions.txt
echo -n "3rdparty " >> /var/www/versions.txt
cd /usr/local/src/owncloud-3rdparty; git log -1 --format="%H" >> /var/www/versions.txt
echo -n "apps " >> /var/www/versions.txt
cd /usr/local/src/owncloud-apps; git log -1 --format="%H" >> /var/www/versions.txt
```

I'm not at home so I can't test this. Note that this does not work when using local copies. You have to find an another solution for this.

I propose creating and executing the above script in the ownCloud recipe (recipes/default.rb) after line 256 and copying a file with the content

```
core: local
3rdparty: local
apps: local
```

to /var/www/versions.txt at line 219.

Any questions?

**Comment by DeepDiver1975** [comment]
Awesome @jakobsack !
I also cannot test this - see you tonight! THX
