### ISSUE TITLE
Create folder in the test

### ISSUE THREAD

**Issue by Gomez** [owncloud-archive/acceptance-testing#27]
The "I have uploaded the "demo" files" cant create folder right now. We need to test this too.

**Comment by Gomez** [comment]
Wait, its not possible to upload a folder over the web...

**Comment by Gomez** [comment]
?

**Comment by Gomez** [comment]
I have done some unfinished work here:

https://github.com/owncloud/acceptance-testing/tree/create_directories_feature

Can be a approach...

**Comment by PVince81** [comment]
Uploading a folder with a web browser only works on Chrome at the moment.

Can you maybe make a pull request from that branch ? (with WIP tag if it's not finished) :smile:

**Comment by PVince81** [comment]
Correction: on OC7 we made it possible to upload folders with Chrome (Chrome is the only browser that implements APIs that allow this)

**Comment by Gomez** [comment]
This was just the create folders feature, its already in master. Wasn't a problem with oc... 
I will delete this branch
