### ISSUE TITLE
Don't get the sources from gitorious!

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud-archive/acceptance-testing#6]
https://github.com/owncloud/acceptance-testing/blob/master/Vagrant/modules/sources/manifests/master.pp

gitorious is still referenced!

let's grab the code from github now

**Comment by diederikdehaas** [comment]
It's also referenced in
https://github.com/owncloud/acceptance-testing/blob/master/Vagrant/README.txt

**Comment by diederikdehaas** [comment]
The README.txt in the Vagrant directory still references gitorious
